from dataclasses import dataclass


@dataclass
class ParametersModel:
    name: str
    in_: str
    description: str
    required: bool
    schema: dict
    example: str
    examples: dict
    style: str
    explode: bool
    allow_empty_value: bool
    allow_reserved: bool
    deprecated: bool
    allow_none: bool
    format: str
    items: dict
    collection_format: str
    default: str
    maximum: int
    exclusive_maximum: bool
    minimum: int
    exclusive_minimum: bool
    max_length: int
    min_length: int
    pattern: str
    max_items: int
    min_items: int
    unique_items: bool
    enum: list
    multiple_of: int
    ref: str
    nullable: bool
    all_of: dict
    one_of: dict
    any_of: dict
    not_: dict
    properties: dict
    additional_properties: dict
    required_: list
    discriminator: dict
    xml: dict
    external_docs: dict
    example_: str
    deprecated_: bool
    allow_none_: bool
    format_: str
    items_: dict
    collection_format_: str
    default_: str
    maximum_: int
    exclusive_maximum_: bool
    minimum_: int
    exclusive_minimum_: bool
    max_length_: int
    min_length_: int
    pattern_: str
    max_items_: int
    min_items_: int
    unique_items_: bool
    enum_: list
    multiple_of_: int
    ref_: str
    nullable_: bool
    all_of_: dict
    one_of_: dict
    any_of_: dict
    not__: dict
    properties_: dict
    additional_properties_: dict
    required__: list
    discriminator_: dict
    xml_: dict
    external_docs_: dict
    example__: str
    deprecated__: bool
    allow_none__: bool
    format__: str
    items__: dict
    collection_format__: str
    default__: str
    maximum__: int
    exclusive_maximum__: bool
    minimum__: int
    exclusive_minimum__: bool
    max_length__: int
    min_length__: int
    pattern__: str
    max_items__: int
    min_items__: int
    unique_items__: bool
    enum__: list
    multiple_of__: int
