import requests


class RequestHelper:
    def __init__(self, http_model):
        """
        Helper class to make requests to the server
        :param http_model: an instance of a class generated by the OOP generator
        """
        self.path_params = http_model.path_params or {}
        self.request_args = http_model.request_args or {}
        self.url = http_model.SERVER + http_model.PATH
        self.response = None
        self.metrics = None

    def set_path_params(self, params):
        self.path_params = params

    def set_query_params(self, params):
        self.request_args['params'] = params

    def set_header_params(self, params):
        self.request_args['headers'] = params

    def set_cookie_params(self, params):
        self.request_args['cookies'] = params

    def make_request(self):
        self.url = self.replace_placeholders(self.url)

        if self.request_args:
            self.response = requests.get(self.url,
                                         **self.request_args)
        else:
            self.response = requests.get(self.url)

        self.metrics = {
            "response_time": self.response.elapsed.total_seconds(),
            "status_code": self.response.status_code,
            "content_type": self.response.headers["Content-Type"],
            "content_length": self.response.headers[
                "Content-Length"],
        }

    def replace_placeholders(self, url: str) -> str:
        for key, value in self.path_params.items():
            url = url.replace(f"{{{key}}}", str(value))
        return url
