import requests


class RequestHelper:
    def __init__(self, interface):
        """
        Helper class to make requests to the server
        :param interface: an instance of a class generated by the OOP generator
        """
        self.interface = interface

    def set_path_params(self, params):
        self.interface.path_params = params

    def set_query_params(self, params):
        self.interface.request_args['params'] = params

    def set_header_params(self, params):
        self.interface.request_args['headers'] = params

    def set_cookie_params(self, params):
        self.interface.request_args['cookies'] = params

    def make_request(self):
        self.interface.url = self.replace_placeholders(self.interface.url)

        if self.interface.request_args:
            self.interface.response = requests.get(self.interface.url,
                                                   **self.interface.request_args)
        else:
            self.interface.response = requests.get(self.interface.url)

        self.interface.metrics = {
            "response_time": self.interface.response.elapsed.total_seconds(),
            "status_code": self.interface.response.status_code,
            "content_type": self.interface.response.headers["Content-Type"],
            "content_length": self.interface.response.headers[
                "Content-Length"],
        }

    def replace_placeholders(self, url: str) -> str:
        for key, value in self.interface.path_params.items():
            url = url.replace(f"{{{key}}}", str(value))
        return url
